import { type Discente } from "@gestionale/types";
import { validateCF, validateEmail } from "./validators";

export type DiscenteRow = Omit<Discente, "createdAt" | "updatedAt" | "deletedAt">;

export interface ValidationResult {
  valid: DiscenteRow[];
  errors: Array<{ line: number; field: string; value: any; message: string }>;
}

export function validateDiscentiRows(
  rows: Record<string, any>[]
): ValidationResult {
  const valid: DiscenteRow[] = [];
  const errors: Array<{ line: number; field: string; value: any; message: string }> = [];
  const seenCFs = new Set<string>();

  rows.forEach((row, idx) => {
    const line = idx + 2; // Header is line 1

    // Validate CF
    if (!row.codicefiscale || typeof row.codicefiscale !== "string") {
      errors.push({
        line,
        field: "codiceFiscale",
        value: row.codicefiscale,
        message: "Codice Fiscale is required",
      });
      return;
    }

    const cf = row.codicefiscale.toUpperCase().trim();
    if (!validateCF(cf)) {
      errors.push({
        line,
        field: "codiceFiscale",
        value: cf,
        message: "Invalid Codice Fiscale format",
      });
      return;
    }

    if (seenCFs.has(cf)) {
      errors.push({
        line,
        field: "codiceFiscale",
        value: cf,
        message: "Duplicate Codice Fiscale in file",
      });
      return;
    }
    seenCFs.add(cf);

    // Validate cognome
    if (!row.cognome || typeof row.cognome !== "string") {
      errors.push({
        line,
        field: "cognome",
        value: row.cognome,
        message: "Cognome is required",
      });
      return;
    }

    // Validate nome
    if (!row.nome || typeof row.nome !== "string") {
      errors.push({
        line,
        field: "nome",
        value: row.nome,
        message: "Nome is required",
      });
      return;
    }

    // Validate email (optional but if present must be valid)
    if (row.email && !validateEmail(row.email)) {
      errors.push({
        line,
        field: "email",
        value: row.email,
        message: "Invalid email format",
      });
      return;
    }

    // Validate dataNascita (optional but if present must be valid date)
    let dataNascita: Date | null = null;
    if (row.datanascita) {
      if (typeof row.datanascita === "number") {
        // Excel date serial
        dataNascita = excelDateToDate(row.datanascita);
      } else if (typeof row.datanascita === "string") {
        dataNascita = parseDataItaliana(row.datanascita);
      }

      if (!dataNascita || isNaN(dataNascita.getTime())) {
        errors.push({
          line,
          field: "dataNascita",
          value: row.datanascita,
          message: "Invalid date format",
        });
        return;
      }
    }

    // All validations passed
    valid.push({
      id: "", // Will be generated by DB
      matricola: row.matricola || undefined,
      cognome: row.cognome.trim(),
      nome: row.nome.trim(),
      dataNascita: dataNascita || undefined,
      luogoNascita: row.luogonascita || undefined,
      provinciaNascita: row.provincianascita || undefined,
      regioneNascita: row.regionenascita || undefined,
      codiceFiscale: cf,
      email: row.email?.trim() || undefined,
      cellulare: row.cellulare?.trim() || undefined,
      sesso: row.sesso || undefined,
      indirizzoResidenza: row.indirizzoresidenza || undefined,
      capResidenza: row.capresidenza || undefined,
      cittaResidenza: row.cittaresidenza || undefined,
      provinciaResidenza: row.provinciaresidenza || undefined,
      regioneResidenza: row.regioneresidenza || undefined,
      mansione: row.mansione || undefined,
      codiceAteco: row.codiceateco || undefined,
      aziendaId: "", // Will be looked up or created
    });
  });

  return { valid, errors };
}

function excelDateToDate(excelDate: number): Date {
  const date = new Date((excelDate - 25569) * 86400 * 1000);
  return date;
}

// `new Date("23/12/1990")` interpreta MM/DD/YYYY (US): fallisce per giorni
// >12, e per giorni <=12 inverte silenziosamente giorno/mese senza errore
// — bug reale, i file italiani (xlsx export gestionali esterni) sono
// sempre GG/MM/AAAA. Parsing esplicito invece di affidarsi al costruttore
// Date ambiguo.
function parseDataItaliana(value: string): Date | null {
  const match = value.trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (match) {
    const [, giorno, mese, anno] = match;
    const date = new Date(Number(anno), Number(mese) - 1, Number(giorno));
    return isNaN(date.getTime()) ? null : date;
  }
  // Fallback per altri formati (es. ISO YYYY-MM-DD) dove non c'è ambiguità
  const fallback = new Date(value);
  return isNaN(fallback.getTime()) ? null : fallback;
}
